### ISSUE TITLE
[1.18.2] Crop and Sapling Blacklist

### ISSUE THREAD

**Issue by Switch-Back18** [xyroc/DungeonCrawl#146] opened 2023-05-20 07:45 UTC
Hi, I created a modpack and I see Mystical Agriculture seeds being generated in the agriculture rooms.

Is there a configuration that can block the generation of seeds and saplings in some mods ?

Thanks

**Comment by xyroc** [comment] 2024-04-16 14:21
Duplicate of #112

**Closed as not planned by xyroc** 2024-04-16 14:21 UTC
