### ISSUE TITLE
[SUGGESTION] COMPATIBILITY WITH TERRAFIRMACRAFT

### ISSUE THREAD

**Issue by Elianthony** [xyroc/DungeonCrawl#144] opened 2023-04-24 03:41 UTC
Hi! First, thanks for the awesome work in this wonderful mod! Second i suggest config option in mod for 1.18.2 for to able compatibility with terrafirmacraft for generate or configurate any structures to spawn in the biome of tfc:tng.

**Comment by xyroc** [comment] 2024-04-16 14:22
Duplicate of #137

**Closed as not planned by xyroc** 2024-04-16 14:22 UTC
