### ISSUE TITLE
Dungeons spawn in Middle Earth even when the overworld is the only dimension in the whitelist

### ISSUE THREAD

**Issue by WordStormRose** [xyroc/DungeonCrawl#96] opened 2021-09-09 00:51 UTC
As the title says, I have been seeing these dungeons spawning in Middle Earth when I play with both this and the Lord of the Rings mod Renewed, even though the overworld is the only dimension in the whitelist.

**Comment by JoelZBub** [comment] 2021-09-10 00:34
Duplicate of #91

**Closed as completed** 2021-09-11 17:26 UTC
Labels: duplicate
