### ISSUE TITLE
Using /locate dungeoncrawl:dungeon in any non-vanilla dimension will cause the world to get stuck forever. (1.15.2)

### ISSUE THREAD

**Issue by TelepathicGrunt** [xyroc/DungeonCrawl#28] opened 2020-04-09 19:29 UTC
When in any non-vanilla dimension, trying to find DungeonCrawl's dungeon with the locate command will make the world hang forever. This is a new issue report of https://github.com/XYROC/DungeonCrawl/issues/19 but this time, this issue has the correct info and proof that this issue still exists in the latest version of DungeonCrawl and has nothing to do with Dimensional Dungeons. 

Here is the following video showing the hang when using DungeonCrawl with Good Night's Sleep mod (but this will occur with any dimension mod). In the video, I show that only DungeonCrawl and Good Night's Sleep is on, that using /locate in overworld works, but then using /locate in GNS's dimension makes the world hang forever (no loading, mobs gets stuck, chat is unresponsive, etc)
https://streamable.com/jw17ip

The hang can be reproduced with many dimension mods including:
Good Night's Sleep
The Midnight
Gaia Dimension
Ultra Amplified Dimension
World Blender

Oddly enough, it also occurs with Biome O' Plenty when using /locate dungeoncrawl:dungeon in the Nether. 

And there appears to be nothing in the logs when I checked it so it isn't a crash or error being throw but rather, it seems to be an infinite loop somewhere. Most likely has to do with determining if the chunk/biome can spawn the structure.

I hope this helps!

**Comment by Divineaspect** [comment] 2020-05-19 20:08
This is also occurring on 1.14 with Futurepack's alien planets.
https://pastebin.com/Nf6KS9Km

**Comment by scotty9090** [comment] 2021-01-25 01:20
They generate - just found one in my existing world after adding the mod.  You need to generate new chunks.  An easy way to do find one is to use the /locate command (this is what I did.)

**Comment by TelepathicGrunt** [comment] 2021-01-25 01:24
scotty, /locate does not depend on loaded chunks. It automatically checks chunks way out of view at extreme distances. However, this report was originally for 1.15.2. Things changed with certain structure stuff in 1.16.2+ so it should've been less likely that this bug would be accidentally ported to 1.16.2+. It's also months old so maybe a later 1.15.2 release of this mod fixed the bug.  

taking one look at this ancient report again and what I originally described, it seems like the original bug was due to dimensions with a custom biome provider. Probably due to the structure being added to all biomes but did a dimension check somewhere which prevented spawning in that other dimension. This shouldn't happen at all in 1.16.2+ as dimension blacklisting is much easier and very easy to do in worldevent.load in a safe manner.

**Comment by scotty9090** [comment] 2021-01-25 06:10
At no point did I state or imply that /locate depended on loaded chunks.  I was saying this is how I found a dungeon - which was in fact in a yet to be generated chunk.

If the issue is resolved then you should close it.

**Comment by TelepathicGrunt** [comment] 2021-01-25 14:01
Again, it's months old lol. i even forgot this existed. I can check later today if it still persists in 1.16.2+.

**Closed as completed** 2021-05-18 21:48 UTC
Labels: bug
