### ISSUE TITLE
[SUGGESTION] Sapling Config (1.16.5)

### ISSUE THREAD

**Issue by Syrikal** [xyroc/DungeonCrawl#140] opened 2023-02-11 16:33 UTC
Saplings for non-Overworld trees are spawning in the seed/flowerpot rooms, which breaks my modpack's progression a little. I'd appreciate a blacklist option. Thank you for your consideration!

**Comment by xyroc** [comment] 2024-04-16 14:21
Duplicate of #112

**Closed as not planned by xyroc** 2024-04-16 14:21 UTC
Labels: enhancement
